homepage: "https://github.com/VirusTotal/yara"
language: c++
primary_contact: "sahilsalunkhe@tamu.edu"
auto_ccs:
  - "sahilsalunkhe@tamu.edu"
sanitizers:
  - address
  - undefined
fuzzing_engines:
  - libfuzzer
architectures:
  - x86_64
main_repo: "https://github.com/VirusTotal/yara"