homepage: "https://github.com/VirusTotal/yara"
language: c++
primary_contact: "sahilsalunkhe@tamu.edu"
auto_ccs:
  - "sahilsalunkhe@tamu.edu"
sanitizers:
  - address
  - undefined
  - memory
fuzzing_engines:
  - libfuzzer
architectures:
  - x86_64
main_repo: "https://github.com/VirusTotal/yara"


# Optional: specify seed corpus (if you have one)
seed_corpus:
  - ./build/corpus/yara/yara_rules_fuzzer

# Optional: specify fuzz targets (if you have multiple)
fuzz_targets:
  - ./projects/yara/yara_rules_fuzzer